// Import stylesheets
import './style.css';

// Write Javascript code!
const appDiv = document.getElementById('app');
appDiv.innerHTML = `<h1>JS Starter</h1>`;

// 成品代码
const productList = [
  {
    compensateFee: 2342,
    compensateNum: 6628,
    dailyCount: 3003,
    dailyRent: 8206,
    dailyWeightRent: 6052,
    dateCellRowSpan: 16,
    driveFee: 1862,
    id: 1,
    installFee: 8481,
    leaseRange: 1530,
    orderType: '发货',
    orderTypeCellRowSpan: 8,
    productCategory: '盘扣',
    productCategoryRowSpan: 4,
    productName: '立杆',
    productNameRowSpan: 2,
    productNum: 2110,
    productType: 5212,
    productWeight: 1718,
    repairFee: 7474,
    sectionCount: 7468,
    sectionFee: 2496,
    statDate: '2021-09-07',
  },
  {
    compensateFee: 2342,
    compensateNum: 6628,
    dailyCount: 3003,
    dailyRent: 8206,
    dailyWeightRent: 6052,
    dateCellRowSpan: 16,
    driveFee: 1862,
    id: 1,
    installFee: 8481,
    leaseRange: 1530,
    orderType: '发货',
    orderTypeCellRowSpan: 8,
    productCategory: '盘扣',
    productCategoryRowSpan: 4,
    productName: '立杆',
    productNameRowSpan: 2,
    productNum: 2110,
    productType: 5212,
    productWeight: 1718,
    repairFee: 7474,
    sectionCount: 7468,
    sectionFee: 2496,
    statDate: '2021-09-07',
  },
];

const originList = [
  {
    statDate: '2021-09-07',
    children: [
      {
        orderType: '发货1',
        children: [
          {
            productCategory: '盘扣1',
            children: [
              {
                productName: '立杆1',
                children: [
                  {
                    compensateFee: 2342,
                    compensateNum: 6628,
                    dailyCount: 3003,
                    dailyRent: 8206,
                    dailyWeightRent: 6052,
                    driveFee: 1862,
                    id: 1,
                    installFee: 8481,
                    leaseRange: 1530,
                    orderType: '发货',
                    productCategory: '盘扣',
                    productName: '立杆',
                    productNum: 2110,
                    productType: 5212,
                    productWeight: 1718,
                    repairFee: 7474,
                    sectionCount: 7468,
                    sectionFee: 2496,
                    statDate: '2021-09-07',
                  },
                  {
                    compensateFee: 2342,
                    compensateNum: 6628,
                    dailyCount: 3003,
                    dailyRent: 8206,
                    dailyWeightRent: 6052,
                    driveFee: 1862,
                    id: 1,
                    installFee: 8481,
                    leaseRange: 1530,
                    orderType: '发货',
                    productCategory: '盘扣',
                    productName: '立杆',
                    productNum: 2110,
                    productType: 5212,
                    productWeight: 1718,
                    repairFee: 7474,
                    sectionCount: 7468,
                    sectionFee: 2496,
                    statDate: '2021-09-07',
                  },
                ],
              },
              {
                productName: '立杆2',
                children: [
                  {
                    compensateFee: 2342,
                    compensateNum: 6628,
                    dailyCount: 3003,
                    dailyRent: 8206,
                    dailyWeightRent: 6052,
                    driveFee: 1862,
                    id: 1,
                    installFee: 8481,
                    leaseRange: 1530,
                    orderType: '发货',
                    productCategory: '盘扣',
                    productName: '立杆',
                    productNum: 2110,
                    productType: 5212,
                    productWeight: 1718,
                    repairFee: 7474,
                    sectionCount: 7468,
                    sectionFee: 2496,
                    statDate: '2021-09-07',
                  },
                  {
                    compensateFee: 2342,
                    compensateNum: 6628,
                    dailyCount: 3003,
                    dailyRent: 8206,
                    dailyWeightRent: 6052,
                    driveFee: 1862,
                    id: 1,
                    installFee: 8481,
                    leaseRange: 1530,
                    orderType: '发货',
                    productCategory: '盘扣',
                    productName: '立杆',
                    productNum: 2110,
                    productType: 5212,
                    productWeight: 1718,
                    repairFee: 7474,
                    sectionCount: 7468,
                    sectionFee: 2496,
                    statDate: '2021-09-07',
                  },
                ],
              },
            ],
          },
          {
            productCategory: '盘扣2',
            children: [
              {
                productName: '立杆3',
                children: [
                  {
                    compensateFee: 2342,
                    compensateNum: 6628,
                    dailyCount: 3003,
                    dailyRent: 8206,
                    dailyWeightRent: 6052,
                    driveFee: 1862,
                    id: 1,
                    installFee: 8481,
                    leaseRange: 1530,
                    orderType: '发货',
                    productCategory: '盘扣',
                    productName: '立杆',
                    productNum: 2110,
                    productType: 5212,
                    productWeight: 1718,
                    repairFee: 7474,
                    sectionCount: 7468,
                    sectionFee: 2496,
                    statDate: '2021-09-07',
                  },
                  {
                    compensateFee: 2342,
                    compensateNum: 6628,
                    dailyCount: 3003,
                    dailyRent: 8206,
                    dailyWeightRent: 6052,
                    driveFee: 1862,
                    id: 1,
                    installFee: 8481,
                    leaseRange: 1530,
                    orderType: '发货',
                    productCategory: '盘扣',
                    productName: '立杆',
                    productNum: 2110,
                    productType: 5212,
                    productWeight: 1718,
                    repairFee: 7474,
                    sectionCount: 7468,
                    sectionFee: 2496,
                    statDate: '2021-09-07',
                  },
                ],
              },
              {
                productName: '立杆4',
                children: [
                  {
                    compensateFee: 2342,
                    compensateNum: 6628,
                    dailyCount: 3003,
                    dailyRent: 8206,
                    dailyWeightRent: 6052,
                    driveFee: 1862,
                    id: 1,
                    installFee: 8481,
                    leaseRange: 1530,
                    orderType: '发货',
                    productCategory: '盘扣',
                    productName: '立杆',
                    productNum: 2110,
                    productType: 5212,
                    productWeight: 1718,
                    repairFee: 7474,
                    sectionCount: 7468,
                    sectionFee: 2496,
                    statDate: '2021-09-07',
                  },
                  {
                    compensateFee: 2342,
                    compensateNum: 6628,
                    dailyCount: 3003,
                    dailyRent: 8206,
                    dailyWeightRent: 6052,
                    driveFee: 1862,
                    id: 1,
                    installFee: 8481,
                    leaseRange: 1530,
                    orderType: '发货',
                    productCategory: '盘扣',
                    productName: '立杆',
                    productNum: 2110,
                    productType: 5212,
                    productWeight: 1718,
                    repairFee: 7474,
                    sectionCount: 7468,
                    sectionFee: 2496,
                    statDate: '2021-09-07',
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        orderType: '发货2',
        children: [
          {
            productCategory: '盘扣',
            children: [
              {
                productName: '立杆',
                children: [
                  {
                    compensateFee: 2342,
                    compensateNum: 6628,
                    dailyCount: 3003,
                    dailyRent: 8206,
                    dailyWeightRent: 6052,
                    driveFee: 1862,
                    id: 1,
                    installFee: 8481,
                    leaseRange: 1530,
                    orderType: '发货',
                    productCategory: '盘扣',
                    productName: '立杆',
                    productNum: 2110,
                    productType: 5212,
                    productWeight: 1718,
                    repairFee: 7474,
                    sectionCount: 7468,
                    sectionFee: 2496,
                    statDate: '2021-09-07',
                  },
                  {
                    compensateFee: 2342,
                    compensateNum: 6628,
                    dailyCount: 3003,
                    dailyRent: 8206,
                    dailyWeightRent: 6052,
                    driveFee: 1862,
                    id: 1,
                    installFee: 8481,
                    leaseRange: 1530,
                    orderType: '发货',
                    productCategory: '盘扣',
                    productName: '立杆',
                    productNum: 2110,
                    productType: 5212,
                    productWeight: 1718,
                    repairFee: 7474,
                    sectionCount: 7468,
                    sectionFee: 2496,
                    statDate: '2021-09-07',
                  },
                ],
              },
              {
                productName: '立杆',
                children: [
                  {
                    compensateFee: 2342,
                    compensateNum: 6628,
                    dailyCount: 3003,
                    dailyRent: 8206,
                    dailyWeightRent: 6052,
                    driveFee: 1862,
                    id: 1,
                    installFee: 8481,
                    leaseRange: 1530,
                    orderType: '发货',
                    productCategory: '盘扣',
                    productName: '立杆',
                    productNum: 2110,
                    productType: 5212,
                    productWeight: 1718,
                    repairFee: 7474,
                    sectionCount: 7468,
                    sectionFee: 2496,
                    statDate: '2021-09-07',
                  },
                  {
                    compensateFee: 2342,
                    compensateNum: 6628,
                    dailyCount: 3003,
                    dailyRent: 8206,
                    dailyWeightRent: 6052,
                    driveFee: 1862,
                    id: 1,
                    installFee: 8481,
                    leaseRange: 1530,
                    orderType: '发货',
                    productCategory: '盘扣',
                    productName: '立杆',
                    productNum: 2110,
                    productType: 5212,
                    productWeight: 1718,
                    repairFee: 7474,
                    sectionCount: 7468,
                    sectionFee: 2496,
                    statDate: '2021-09-07',
                  },
                ],
              },
            ],
          },
          {
            productCategory: '盘扣',
            children: [
              {
                productName: '立杆',
                children: [
                  {
                    compensateFee: 2342,
                    compensateNum: 6628,
                    dailyCount: 3003,
                    dailyRent: 8206,
                    dailyWeightRent: 6052,
                    driveFee: 1862,
                    id: 1,
                    installFee: 8481,
                    leaseRange: 1530,
                    orderType: '发货',
                    productCategory: '盘扣',
                    productName: '立杆',
                    productNum: 2110,
                    productType: 5212,
                    productWeight: 1718,
                    repairFee: 7474,
                    sectionCount: 7468,
                    sectionFee: 2496,
                    statDate: '2021-09-07',
                  },
                  {
                    compensateFee: 2342,
                    compensateNum: 6628,
                    dailyCount: 3003,
                    dailyRent: 8206,
                    dailyWeightRent: 6052,
                    driveFee: 1862,
                    id: 1,
                    installFee: 8481,
                    leaseRange: 1530,
                    orderType: '发货',
                    productCategory: '盘扣',
                    productName: '立杆',
                    productNum: 2110,
                    productType: 5212,
                    productWeight: 1718,
                    repairFee: 7474,
                    sectionCount: 7468,
                    sectionFee: 2496,
                    statDate: '2021-09-07',
                  },
                ],
              },
              {
                productName: '立杆',
                children: [
                  {
                    compensateFee: 2342,
                    compensateNum: 6628,
                    dailyCount: 3003,
                    dailyRent: 8206,
                    dailyWeightRent: 6052,
                    driveFee: 1862,
                    id: 1,
                    installFee: 8481,
                    leaseRange: 1530,
                    orderType: '发货',
                    productCategory: '盘扣',
                    productName: '立杆',
                    productNum: 2110,
                    productType: 5212,
                    productWeight: 1718,
                    repairFee: 7474,
                    sectionCount: 7468,
                    sectionFee: 2496,
                    statDate: '2021-09-07',
                  },
                  {
                    compensateFee: 2342,
                    compensateNum: 6628,
                    dailyCount: 3003,
                    dailyRent: 8206,
                    dailyWeightRent: 6052,
                    driveFee: 1862,
                    id: 1,
                    installFee: 8481,
                    leaseRange: 1530,
                    orderType: '发货',
                    productCategory: '盘扣',
                    productName: '立杆',
                    productNum: 2110,
                    productType: 5212,
                    productWeight: 1718,
                    repairFee: 7474,
                    sectionCount: 7468,
                    sectionFee: 2496,
                    statDate: '2021-09-07',
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    statDate: '2021-09-08',
    children: [
      {
        orderType: '收货1',
        children: [
          {
            productCategory: '架子1',
            children: [
              {
                productName: '横杆1',
                children: [
                  {
                    compensateFee: 2342,
                    compensateNum: 6628,
                    dailyCount: 3003,
                    dailyRent: 8206,
                    dailyWeightRent: 6052,
                    driveFee: 1862,
                    id: 1,
                    installFee: 8481,
                    leaseRange: 1530,
                    orderType: '发货',
                    productCategory: '盘扣',
                    productName: '立杆',
                    productNum: 2110,
                    productType: 5212,
                    productWeight: 1718,
                    repairFee: 7474,
                    sectionCount: 7468,
                    sectionFee: 2496,
                    statDate: '2021-09-07',
                  },
                  {
                    compensateFee: 2342,
                    compensateNum: 6628,
                    dailyCount: 3003,
                    dailyRent: 8206,
                    dailyWeightRent: 6052,
                    driveFee: 1862,
                    id: 1,
                    installFee: 8481,
                    leaseRange: 1530,
                    orderType: '发货',
                    productCategory: '盘扣',
                    productName: '立杆',
                    productNum: 2110,
                    productType: 5212,
                    productWeight: 1718,
                    repairFee: 7474,
                    sectionCount: 7468,
                    sectionFee: 2496,
                    statDate: '2021-09-07',
                  },
                ],
              },
              {
                productName: '横杆2',
                children: [
                  {
                    compensateFee: 2342,
                    compensateNum: 6628,
                    dailyCount: 3003,
                    dailyRent: 8206,
                    dailyWeightRent: 6052,
                    driveFee: 1862,
                    id: 1,
                    installFee: 8481,
                    leaseRange: 1530,
                    orderType: '发货',
                    productCategory: '盘扣',
                    productName: '立杆',
                    productNum: 2110,
                    productType: 5212,
                    productWeight: 1718,
                    repairFee: 7474,
                    sectionCount: 7468,
                    sectionFee: 2496,
                    statDate: '2021-09-07',
                  },
                  {
                    compensateFee: 2342,
                    compensateNum: 6628,
                    dailyCount: 3003,
                    dailyRent: 8206,
                    dailyWeightRent: 6052,
                    driveFee: 1862,
                    id: 1,
                    installFee: 8481,
                    leaseRange: 1530,
                    orderType: '发货',
                    productCategory: '盘扣',
                    productName: '立杆',
                    productNum: 2110,
                    productType: 5212,
                    productWeight: 1718,
                    repairFee: 7474,
                    sectionCount: 7468,
                    sectionFee: 2496,
                    statDate: '2021-09-07',
                  },
                ],
              },
            ],
          },
          {
            productCategory: '架子2',
            children: [
              {
                productName: '横杆3',
                children: [
                  {
                    compensateFee: 2342,
                    compensateNum: 6628,
                    dailyCount: 3003,
                    dailyRent: 8206,
                    dailyWeightRent: 6052,
                    driveFee: 1862,
                    id: 1,
                    installFee: 8481,
                    leaseRange: 1530,
                    orderType: '发货',
                    productCategory: '盘扣',
                    productName: '立杆',
                    productNum: 2110,
                    productType: 5212,
                    productWeight: 1718,
                    repairFee: 7474,
                    sectionCount: 7468,
                    sectionFee: 2496,
                    statDate: '2021-09-07',
                  },
                  {
                    compensateFee: 2342,
                    compensateNum: 6628,
                    dailyCount: 3003,
                    dailyRent: 8206,
                    dailyWeightRent: 6052,
                    driveFee: 1862,
                    id: 1,
                    installFee: 8481,
                    leaseRange: 1530,
                    orderType: '发货',
                    productCategory: '盘扣',
                    productName: '立杆',
                    productNum: 2110,
                    productType: 5212,
                    productWeight: 1718,
                    repairFee: 7474,
                    sectionCount: 7468,
                    sectionFee: 2496,
                    statDate: '2021-09-07',
                  },
                ],
              },
              {
                productName: '横杆4',
                children: [
                  {
                    compensateFee: 2342,
                    compensateNum: 6628,
                    dailyCount: 3003,
                    dailyRent: 8206,
                    dailyWeightRent: 6052,
                    driveFee: 1862,
                    id: 1,
                    installFee: 8481,
                    leaseRange: 1530,
                    orderType: '发货',
                    productCategory: '盘扣',
                    productName: '立杆',
                    productNum: 2110,
                    productType: 5212,
                    productWeight: 1718,
                    repairFee: 7474,
                    sectionCount: 7468,
                    sectionFee: 2496,
                    statDate: '2021-09-07',
                  },
                  {
                    compensateFee: 2342,
                    compensateNum: 6628,
                    dailyCount: 3003,
                    dailyRent: 8206,
                    dailyWeightRent: 6052,
                    driveFee: 1862,
                    id: 1,
                    installFee: 8481,
                    leaseRange: 1530,
                    orderType: '发货',
                    productCategory: '盘扣',
                    productName: '立杆',
                    productNum: 2110,
                    productType: 5212,
                    productWeight: 1718,
                    repairFee: 7474,
                    sectionCount: 7468,
                    sectionFee: 2496,
                    statDate: '2021-09-07',
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        orderType: '收货2',
        children: [
          {
            productCategory: '架子3',
            children: [
              {
                productName: '横杆5',
                children: [
                  {
                    compensateFee: 2342,
                    compensateNum: 6628,
                    dailyCount: 3003,
                    dailyRent: 8206,
                    dailyWeightRent: 6052,
                    driveFee: 1862,
                    id: 1,
                    installFee: 8481,
                    leaseRange: 1530,
                    orderType: '发货',
                    productCategory: '盘扣',
                    productName: '立杆',
                    productNum: 2110,
                    productType: 5212,
                    productWeight: 1718,
                    repairFee: 7474,
                    sectionCount: 7468,
                    sectionFee: 2496,
                    statDate: '2021-09-07',
                  },
                  {
                    compensateFee: 2342,
                    compensateNum: 6628,
                    dailyCount: 3003,
                    dailyRent: 8206,
                    dailyWeightRent: 6052,
                    driveFee: 1862,
                    id: 1,
                    installFee: 8481,
                    leaseRange: 1530,
                    orderType: '发货',
                    productCategory: '盘扣',
                    productName: '立杆',
                    productNum: 2110,
                    productType: 5212,
                    productWeight: 1718,
                    repairFee: 7474,
                    sectionCount: 7468,
                    sectionFee: 2496,
                    statDate: '2021-09-07',
                  },
                ],
              },
              {
                productName: '横杆6',
                children: [
                  {
                    compensateFee: 2342,
                    compensateNum: 6628,
                    dailyCount: 3003,
                    dailyRent: 8206,
                    dailyWeightRent: 6052,
                    driveFee: 1862,
                    id: 1,
                    installFee: 8481,
                    leaseRange: 1530,
                    orderType: '发货',
                    productCategory: '盘扣',
                    productName: '立杆',
                    productNum: 2110,
                    productType: 5212,
                    productWeight: 1718,
                    repairFee: 7474,
                    sectionCount: 7468,
                    sectionFee: 2496,
                    statDate: '2021-09-07',
                  },
                  {
                    compensateFee: 2342,
                    compensateNum: 6628,
                    dailyCount: 3003,
                    dailyRent: 8206,
                    dailyWeightRent: 6052,
                    driveFee: 1862,
                    id: 1,
                    installFee: 8481,
                    leaseRange: 1530,
                    orderType: '发货',
                    productCategory: '盘扣',
                    productName: '立杆',
                    productNum: 2110,
                    productType: 5212,
                    productWeight: 1718,
                    repairFee: 7474,
                    sectionCount: 7468,
                    sectionFee: 2496,
                    statDate: '2021-09-07',
                  },
                ],
              },
            ],
          },
          {
            productCategory: '架子4',
            children: [
              {
                productName: '立杆',
                children: [
                  {
                    compensateFee: 2342,
                    compensateNum: 6628,
                    dailyCount: 3003,
                    dailyRent: 8206,
                    dailyWeightRent: 6052,
                    driveFee: 1862,
                    id: 1,
                    installFee: 8481,
                    leaseRange: 1530,
                    orderType: '发货',
                    productCategory: '盘扣',
                    productName: '立杆',
                    productNum: 2110,
                    productType: 5212,
                    productWeight: 1718,
                    repairFee: 7474,
                    sectionCount: 7468,
                    sectionFee: 2496,
                    statDate: '2021-09-07',
                  },
                  {
                    compensateFee: 2342,
                    compensateNum: 6628,
                    dailyCount: 3003,
                    dailyRent: 8206,
                    dailyWeightRent: 6052,
                    driveFee: 1862,
                    id: 1,
                    installFee: 8481,
                    leaseRange: 1530,
                    orderType: '发货',
                    productCategory: '盘扣',
                    productName: '立杆',
                    productNum: 2110,
                    productType: 5212,
                    productWeight: 1718,
                    repairFee: 7474,
                    sectionCount: 7468,
                    sectionFee: 2496,
                    statDate: '2021-09-07',
                  },
                ],
              },
              {
                productName: '立杆',
                children: [
                  {
                    compensateFee: 2342,
                    compensateNum: 6628,
                    dailyCount: 3003,
                    dailyRent: 8206,
                    dailyWeightRent: 6052,
                    driveFee: 1862,
                    id: 1,
                    installFee: 8481,
                    leaseRange: 1530,
                    orderType: '发货',
                    productCategory: '盘扣',
                    productName: '立杆',
                    productNum: 2110,
                    productType: 5212,
                    productWeight: 1718,
                    repairFee: 7474,
                    sectionCount: 7468,
                    sectionFee: 2496,
                    statDate: '2021-09-07',
                  },
                  {
                    compensateFee: 2342,
                    compensateNum: 6628,
                    dailyCount: 3003,
                    dailyRent: 8206,
                    dailyWeightRent: 6052,
                    driveFee: 1862,
                    id: 1,
                    installFee: 8481,
                    leaseRange: 1530,
                    orderType: '发货',
                    productCategory: '盘扣',
                    productName: '立杆',
                    productNum: 2110,
                    productType: 5212,
                    productWeight: 1718,
                    repairFee: 7474,
                    sectionCount: 7468,
                    sectionFee: 2496,
                    statDate: '2021-09-07',
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
];

let arrObj = {};
let arrList = [];
let idx = 0;

const flatArr = (arr) => {
  ++idx;
  for (let obj of arr) {
    const flat = Object.keys(obj).includes('children');
    if (!flat) {
      console.log(idx);
      const newObj = Object.assign(arrObj, obj);
      arrList.push(Object.assign(arrObj, obj));
      return;
    }
    const { children, ...rest } = obj;
    Object.assign(arrObj, rest);
    console.info(arrObj);
    flatArr(children);
  }
};
flatArr(originList);

console.info(arrList);
